# Generated by Django 4.2.3 on 2023-07-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('audio_file_type', models.CharField(choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('amr', 'AMR'), ('wma', 'WMA')], max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('is_soft_deleted', models.BooleanField(default=False)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('update_upload_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
